/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.4.1/samples
 */

import java.io.ByteArrayOutputStream

val dataFolder = "_data"
val originalFileName = "vocabolangelo.ttl"
val inferredFileName = "vocabolangelo-inferred.xml"

fun filePath(fileName: String) = dataFolder + File.separator + fileName

val originalFilePath = filePath(originalFileName)
val inferredFilePath = filePath(inferredFileName)

tasks.register<Exec>("test") {
    commandLine("turtle", "--validate", originalFilePath)
}

tasks.register("infer") {
    doLast{
        val outputStream = ByteArrayOutputStream()
        exec{
            commandLine("pellet", "extract", originalFilePath)
            standardOutput = outputStream
        }
        File(inferredFilePath).writeText(outputStream.toString())
    }
}
