name: Validate RDF

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
      - name: Validate RDF
        uses: vemonet/jena-riot-action@v3.14
        with:
          input: public/schema/vocabolangelo.ttl
